package heuristics.brkga.client;

import heuristics.brkga.independent.Individual;

/**
 *
 * @author Mirko Alicastro {@link https://mirkoalicastro.com}
 */
@FunctionalInterface
public interface CrossingOver {

    /**
     * Crossover between elite individual and not elite individual.
     * The invocation of this method must modify the not elite individual
     * turning it into the individual generated by the crossover.
     * @param elite elite individual
     * @param notElite not elite individual which will be updated
     */
    void crossover(Individual elite, Individual notElite);
}
